# -*- coding: utf-8 -*-
"""Student_performance_index_Deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QAGeggrFIStRq_IPNgRa__E9XOsdVYPH
"""

# -*- coding: utf-8 -*-
"""student_performance_index_deployement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QAGeggrFIStRq_IPNgRa__E9XOsdVYPH
"""

# Install Streamlit (only needed in Colab/Notebook)
pip install streamlit

import streamlit as st
import joblib
import pandas as pd

# Load trained model
model = joblib.load("student_model.pkl")

st.title("🎓 Student Performance Predictor")

# User Inputs
gender = st.selectbox("Gender", ["Male", "Female"])
hours = st.slider("Hours Studied", 1, 10)
prev_score = st.slider("Previous Score", 40, 100)
extra = st.selectbox("Extracurricular Activities", ["Yes", "No"])
tuition = st.selectbox("Tuition", ["Yes", "No"])
sleep = st.slider("Sleep Hours", 4, 10)
papers = st.slider("Sample Question Papers Practiced", 0, 10)

# Prediction
if st.button("Predict"):
    g = 1 if gender == "Female" else 0
    e = 1 if extra == "Yes" else 0
    t = 1 if tuition == "Yes" else 0

    input_data = pd.DataFrame([[g, hours, prev_score, e, t, sleep, papers]],
                              columns=['Gender', 'Hours Studied', 'Previous Scores',
                                       'Extracurricular Activities', 'Tuition',
                                       'Sleep Hours', 'Sample Question Papers Practiced'])

    prediction = model.predict(input_data)[0]

    st.success(f"🎯 Predicted Performance Index: {round(prediction,2)} / 100")
